cmpcatlab <- c("Foreign Special Rel. +",
               "Foreign Special Rel. -",
               "Anti-Imperial./-Colonial.",
               "Military +",
               "Military -",
               "Peace +",
               "Internationalism +",
               "European Integration +",
               "Internationalism -",
               "European Integration -",
               "Freedom and Hum. Rights +",
               "Democracy +",
               "Constitutionalism +",
               "Constitutionalism -",
               "Decentralisation +",
               "Centralisation +",
               "Gov. and Admin. Effic. +",
               "Political Corruption -",
               "Political Authority +",
               "Free Enterprise +",
               "Incentives +",
               "Market Regulation +",
               "Economic Planning +",
               "Corporatism +",
               "Protectionism +",
               "Protectionism -",
               "Economic Goals",
               "Keynesian Dem. Man. +",
               "Productivity +",
               "Technology and Infrastr. +",
               "Controlled Economy +",
               "Nationalisation +",
               "Economic Orthodoxy +",
               "Marxist Analysis +",
               "Anti-Growth Economy +",
               "Environm. Protection +",
               "Culture +",
               "Social Justice +",
               "Welfare State Expansion +",
               "Welfare State Limitation +",
               "Education Expansion +",
               "Education Limitation +",
               "National Way of Life +",
               "National Way of Life -",
               "Traditional Morality +",
               "Traditional Morality -",
               "Law and Order +",
               "Social Harmony +",
               "Multiculturalism +",
               "Multiculturalism -",
               "Labour Groups +",
               "Labour Groups -",
               "Farmers +",
               "Middle Class, Profess. Gr. +",
               "Underpriv. Minority Gr. +",
               "Non-Econ. Demogr. Gr. +")
